GET http://localhost:5000

### login
POST  http://localhost:5000/auth/login

### register
POST http://localhost:5000/auth/register

### referesh-token
POST http://localhost:5000/auth/referesh-token

### logout
DELETE  http://localhost:5000/auth/logout